# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
app:
  name: flight-cancel
spring:
  profiles:
    active: ${APP}
  main:
    banner-mode: "off"
  jmx:
    enabled: false
  jsp-servlet:
    registered: false
  freemarker:
    enabled: false
  groovy:
    template:
      enabled: false
  mobile:
    sitepreference:
      enabled: false
  thymeleaf:
    cache: false
  data:
    mongodb.uri: mongodb://localhost:27017/flight
    mongo.repositories.enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8077



