
spring.jmx:
  enabled: false

spring:
  data:
    mongodb.uri: mongodb://localhost:27017/trip
    mongo.repositories.enabled: true

server:
  port: 9000


trip:
  flight:
    bookURL: http://localhost:8070/flight
    cancelURL: http://localhost:8077/flight
  hotel:
    bookURL: http://localhost:8090/hotel
    cancelURL: http://localhost:8099/hotel
  car:
    bookURL: http://localhost:8060/car
    cancelURL: http://localhost:8066/car
