# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  main:
    banner-mode: "off"
  jmx:
    enabled: false
  jsp-servlet:
    registered: false
  freemarker:
    enabled: false
  groovy:
    template:
      enabled: false
  mobile:
    sitepreference:
      enabled: false
  thymeleaf:
    cache: false
  data:
    mongodb.uri: mongodb://localhost:27017/trip
    mongo.repositories.enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9000


trip:
  flight:
    bookURL: http://localhost:8070/flight
    cancelURL: http://localhost:8077/flight
  hotel:
    bookURL: http://localhost:8090/hotel
    cancelURL: http://localhost:8099/hotel
  car:
    bookURL: http://localhost:8060/car
    cancelURL: http://localhost:8066/car
